config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'users/registrations'
  }
  resources :rooms, param: :key
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :bigint(8)        not null, primary key
#  key        :string(100)      not null
#  name       :string(150)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)        not null
#
# Indexes
#
#  index_rooms_on_key      (key) UNIQUE
#  index_rooms_on_user_id  (user_id)
#

class Room < ApplicationRecord
  belongs_to :user
  validates :key, uniqueness: true, presence: true

  def generate_key
    tmp_key = SecureRandom.urlsafe_base64(20)
    self.key = self.class.where(:key => tmp_key).blank? ? tmp_key : generate_key
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :destroy]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = Room.new
    @room.generate_key
  end

  def show

  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to rooms_path, notice: "Room: #{@room.name} created."
    else
      @room.generate_key
      render :new
    end
  end

  def destroy
    @room.destroy!
    redirect_to rooms_path, notice: "Room: #{@room.name} deleted."
  end

  private

  def room_params
    params.require(:room).permit(:name, :key)
  end

  def set_room
    @room = Room.find_by!(key: params[:key])
  end

end

app/views/rooms/_webrtc_settings.js.erb
var webrtc = new SimpleWebRTC({
  // the id/element dom element that will hold "our" video
  localVideoEl: 'localVideo',
  // the id/element dom element that will hold remote videos
  remoteVideosEl: '',
  // immediately ask for camera access
  autoRequestMedia: true,
  url: "<%= ENV['WEB_RTC_URL'] %>",
  media: { video: { width: 320, height: 240, frameRate: 20 }, audio: true }
});

// a peer video has been added
webrtc.on('videoAdded', function (video, peer) {
  console.log('video added', peer);
  var remotes = document.getElementById('remotesVideos');
  if (remotes) {
    video.setAttribute("playsinline", true);
    video.className = 'remote-video video';
    var container = document.createElement('div');
    container.className = 'videoContainer';
    container.id = 'container_' + webrtc.getDomId(peer);
    container.appendChild(video);
    remotes.appendChild(container);
  }
});

// a peer video was removed
webrtc.on('videoRemoved', function (video, peer) {
  console.log('video removed ', peer);
  var remotes = document.getElementById('remotesVideos');
  var el = document.getElementById(peer ? 'container_' + webrtc.getDomId(peer) : 'localScreenContainer');
  if (remotes && el) {
    remotes.removeChild(el);
  }
});

webrtc.on('readyToCall', function () {
  // you can name it anything
  webrtc.joinRoom("<%= room_key %>");
});

app/views/rooms/index.html.haml
.row
  .col
    %h1.main__header1
      Meeting Rooms
.row.mb-2
  .col
    = link_to 'New Room', new_room_path, class: 'btn btn-primary'
.row
  .col
    %table.table
      %thead.thead-light
        %tr
          %th
            Name
          %th
            URL
          %th
            Actions
      %tbody
        - @rooms.each do |room|
          %tr
            %td.align-middle
              = room.name
            %td.align-middle
              = room_url(room.key)
            %td.align-middle
              = link_to 'Join Room', room_path(room.key), class: 'btn btn-primary'
              = button_tag 'Copy URL', data: { 'clipboard-text' => room_url(room.key) }, class: 'clipboard-btn btn btn-light'
              = link_to 'Delete', room_path(room.key),method: :delete, data: { confirm: 'Delete this room?' }, class: 'btn btn-light'

app/views/rooms/new.html.haml
.row
  .col
    = render 'application/model_errors', model: @room
.row
  .col
    = form_for @room do |f|
      .form-group
        = f.label 'name'
        = f.text_field 'name', class: 'form-control'
      .form-group
        = f.label 'key'
        = f.text_field 'key', class: 'form-control'
      = f.submit 'Create', class: 'btn btn-primary'

app/views/rooms/show.html.haml
- content_for :header do
  = javascript_include_tag 'https://webrtc.github.io/adapter/adapter-latest.js'
  = javascript_include_tag 'https://simplewebrtc.com/latest-v3.js'
  %script
    = render 'webrtc_settings.js', room_key: @room.key
.row
  .col
    %h1.main__header1
      = "Room Name: #{@room.name || "(none)"}"
.row
  .col
    .text-right
      = link_to 'Back', rooms_path, class: "btn btn-light"
.row
  .col
    .local-video-container
      %video#localVideo{:playsinline => "true"}
.row
  .col
    #remotesVideos